steps:
 - name: 'ubuntu'
  args: ['cp', 'src/main/appengine/app.yaml']
  dir: 'Front-End-AppEngine'
- id: "Deploy to AppEngine"
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  dir: 'Front-End-AppEngine'
timeout: '1600s'
