runtime: nodejs8
#api_version: 1
service: front-end

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /
  static_files: www/
  upload: www/ResourceMapping.js
